### ISSUE TITLE
BUG: Ens lookup does not work with testnet

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape-ens#25]
### Environment information

* `ape` and plugin versions: 

Installed Plugins:
  vyper       0.5.0
  ens         0.5.1
  alchemy     0.5.0
  solidity    0.5.1
  polygon     0.5.0a1

```
$ ape --version

0.5.2

$ ape plugins list
# ...copy and paste result of above command here...
```

* Python Version: Python 3.8.10
* OS: Linux

### What went wrong?

```
ape console --network ethereum:goerli:alchemy

In [1]: from ape.types import AddressType
In [2]: convert("snackoverflow.eth", AddressType)
WARNING: Unable to connect to mainnet provider to perform ENS lookup. Try changing your default mainnet provider.
```
### How can it be fixed?

We should default lookup in mainnet and return the address in the console

**Comment by Ninjagod1251** [comment]
Solution:
Right, you connect to goerli in the console but when it resolves the name, it uses mainnet and that is fine so long as you tell it the provider for mainnet somewhere in the config

--Jules



```
ethereum:
  mainnet:
    default_provider: alchemy
 ```

**Comment by antazoey** [comment]
It uses your default mainnet, as you pointed out! And since then, Ape tries to find better URLs using evmchains when you havent set one, so more chance of success
