### ISSUE TITLE
bug: ENS plugin only works on mainnet

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-ens#7]
### Environment information

Latest and greatest ape and ens plugin

* Python Version: 3.10.1
* OS: maco

### What went wrong?

ENS plugins only works on mainnet

### How can it be fixed?

If not connected to mainnet, create a side-connecton to mainnet for this plugin's use only

**Comment by fubuloubu** [comment]
Solution is to use `NetworkManager` to connect to Ethereum mainnet to do the lookup.

We should do this instead of relying on Web3py's built-in ENS lookup, because apparently it is buggy

**Comment by unparalleled-js** [comment]
> 

Stuff I am trying to still figure out:

1. Which provider does `NetworkManager` user to connect to mainnet? Currently, we only have a default provider, which is usually a local provider, so that wouldn't work to use the default. My thought is allow it to be set in the config, otherwise pick the first provider that is not a `TestProviderAPI`.

2. Is this plugin always connected to mainnet or does it only connect during calls to `is_convertible()` and `convert()`?

**Comment by fubuloubu** [comment]
1. `with network_manager.parse_network_choice("ethereum:mainnet") as provider: ...`
2. Only during `is_convertible`/`convert`

**Comment by fubuloubu** [comment]
Note: one of the original reasons I wanted a context manager here
